### ISSUE TITLE
Open up the repository for contribution

### ISSUE THREAD

**Issue by steebe** [fossas/commons-clause#2]
Hi there!

I've cloned this project to make some spelling/grammar corrections & would like to push the changes for you to review, but this project is locked down. Are you open to considering granting the public permission to push to the repository at all? 

Best,
steebe

**Comment by mikemaccana** [comment]
They have PR's open, I've sent one: https://github.com/fossas/commons-clause/pulls

**Comment by xizhao** [comment]
I'm not aware of how it's locked down, I think PR submissions are open?

**Comment by steebe** [comment]
Hmmm... I'm unable to push to the remote with a new branch ¯\_(ツ)_/¯
